export const FREE_LIMITS = {
  MAX_WARDROBE_ITEMS: 30,
  DAILY_OUTFIT_SUGGESTIONS: 3,
  BUY_DECISIONS_PER_MONTH: 5,
  PRICE_TRACKING_ITEMS: 3,
  FRIENDS: 0,
  ANALYTICS_FULL: false,
  EVENT_PLANNING: false,
} as const;

export const PREMIUM_LIMITS = {
  MAX_WARDROBE_ITEMS: Number.POSITIVE_INFINITY,
  DAILY_OUTFIT_SUGGESTIONS: Number.POSITIVE_INFINITY,
  BUY_DECISIONS_PER_MONTH: Number.POSITIVE_INFINITY,
  PRICE_TRACKING_ITEMS: Number.POSITIVE_INFINITY,
  FRIENDS: Number.POSITIVE_INFINITY,
  ANALYTICS_FULL: true,
  EVENT_PLANNING: true,
} as const;

export type LimitKey = keyof typeof FREE_LIMITS;
